# Generated by Django 4.2.6 on 2023-12-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_task_options_alter_task_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='kolvo',
        ),
        migrations.RemoveField(
            model_name='task',
            name='products',
        ),]
